// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreateGroupHandlerFunc turns a function with the right signature into a create group handler
type CreateGroupHandlerFunc func(CreateGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreateGroupHandlerFunc) Handle(params CreateGroupParams) middleware.Responder {
	return fn(params)
}

// CreateGroupHandler interface for that can handle valid create group params
type CreateGroupHandler interface {
	Handle(CreateGroupParams) middleware.Responder
}

// NewCreateGroup creates a new http.Handler for the create group operation
func NewCreateGroup(ctx *middleware.Context, handler CreateGroupHandler) *CreateGroup {
	return &CreateGroup{Context: ctx, Handler: handler}
}

/*CreateGroup swagger:route POST /groups createGroup

CreateGroup create group API

*/
type CreateGroup struct {
	Context *middleware.Context
	Handler CreateGroupHandler
}

func (o *CreateGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreateGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
