// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetGroupHandlerFunc turns a function with the right signature into a get group handler
type GetGroupHandlerFunc func(GetGroupParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGroupHandlerFunc) Handle(params GetGroupParams) middleware.Responder {
	return fn(params)
}

// GetGroupHandler interface for that can handle valid get group params
type GetGroupHandler interface {
	Handle(GetGroupParams) middleware.Responder
}

// NewGetGroup creates a new http.Handler for the get group operation
func NewGetGroup(ctx *middleware.Context, handler GetGroupHandler) *GetGroup {
	return &GetGroup{Context: ctx, Handler: handler}
}

/*GetGroup swagger:route GET /groups/{groupName} getGroup

GetGroup get group API

*/
type GetGroup struct {
	Context *middleware.Context
	Handler GetGroupHandler
}

func (o *GetGroup) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetGroupParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
