// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	strfmt "github.com/go-openapi/strfmt"

	models "PlanetLabs/AuthService/models"
)

// NewUpdateGroupParams creates a new UpdateGroupParams object
// no default values defined in spec.
func NewUpdateGroupParams() UpdateGroupParams {

	return UpdateGroupParams{}
}

// UpdateGroupParams contains all the bound params for the update group operation
// typically these are obtained from a http.Request
//
// swagger:parameters UpdateGroup
type UpdateGroupParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*
	  Required: true
	  In: body
	*/
	UpdateGroupInput *models.GroupList
	/*
	  Required: true
	  In: path
	*/
	GroupName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewUpdateGroupParams() beforehand.
func (o *UpdateGroupParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.GroupList
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("updateGroupInput", "body"))
			} else {
				res = append(res, errors.NewParseError("updateGroupInput", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.UpdateGroupInput = &body
			}
		}
	} else {
		res = append(res, errors.Required("updateGroupInput", "body"))
	}
	rGroupName, rhkGroupName, _ := route.Params.GetOK("groupName")
	if err := o.bindGroupName(rGroupName, rhkGroupName, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindGroupName binds and validates parameter GroupName from path.
func (o *UpdateGroupParams) bindGroupName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	o.GroupName = raw

	return nil
}
